Round timestamps to the nearest integer
bugsnag/bugsnag-js-performance pull request #364
Opened 2023-10-26 10:23 UTC by yousif-bugsnag

## Goal

Browser timing APIs usually return a `DOMHighResTimestamp` (aka a double). These values are usually integers (i.e. whole milliseconds) but it is valid for them to contain a fractional part, representing nanoseconds

Currently we don’t do anything to handle this, which results in our encoded JSON payloads being invalid according to the OTEL spec

This PR updates the millisecond to nanosecond conversion to round nanoseconds to the nearest integer to ensure we always send a valid payload.

## Design

`performance.now` on React Native also returns a double, so went for implementing this in the core `millisecondsToNanoseconds` function as this is used to convert millisecond values by both of the platform-specific clocks

2023-10-26 10:31 UTC, imjoehaines approved these changes

2023-10-26 10:31 UTC, imjoehaines commented on packages/core/tests/clock.test.ts
> +  it('rounds to the nearest integer', () => {
nit:

```suggestion
  it('rounds to the nearest nanosecond', () => {
```

2023-10-26 10:31 UTC, imjoehaines commented on packages/core/tests/clock.test.ts
> +  it('rounds to the nearest integer', () => {
just to be a bit clearer what we're actually trying to achieve

2023-10-26 15:17 UTC, gingerbenw approved these changes

2023-10-26 15:18 UTC, gingerbenw requested changes
Changelog!

2023-10-27 13:07 UTC, gingerbenw approved these changes

2023-10-27 13:33 UTC, merged